apiVersion: v1
kind: ConfigMap
metadata:
  name: ec2-instance-dev
data:
  create-ec2.sh: |
    #!/bin/bash
    echo "🚀 Launching EC2 instance for dev environment"
    aws ec2 run-instances \
      --region us-east-2 \
      --image-id ami-077b630ef539aa0b5 \
      --instance-type t3.micro \
      --key-name jenkins \
      --security-groups terraform-20251020023708191800000002 \
      --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=ec2-lab-dev},{Key=Environment,Value=dev}]"
