replicaCount: 1

image:
  tag: "1.25.3"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: "dev.example.com"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
